Repository melikechan/degoogle-turkish, pull requests merged in 2021-02, with the labels that each got.

#9 Added translation issue template
  .github/ISSUE_TEMPLATE/add-improve-translation.md
  README.md
Labels: enhancement

#12 Fixed accidental deletion
  .github/ISSUE_TEMPLATE/add-improve-translation.md
  CONTRIBUTORS.md
  README.md
  md/_closingRemarks.md
  md/_contributing.md
  md/_disclaimer.md
  md/_header.md
  md/_index.md
  md/_lighterSide.md
  md/_resources.md
  yaml/bloglar.yml
  yaml/kitaplar.yml
  yaml/tarayıcıEklentileri.yml
Labels: bug, documentation

#15 tercüme eklemeleri ve düzeltmeleri
  md/_closingRemarks.md
  md/_contributing.md
  md/_disclaimer.md
  md/_index.md
  md/_lighterSide.md
Labels: documentation

#16 Merging to translation branch
  CONTRIBUTORS.md
  README.md
  md/_closingRemarks.md
  md/_contributing.md
  md/_disclaimer.md
  md/_index.md
  md/_lighterSide.md
Labels: minor change

#17 Added minor translations to degoogle.yml
  yaml/degoogle.yml
Labels: minor change

#19 Fixed deadlinks in _index.md
  _build.js
  md/_disclaimer.md
  md/_index.md
Labels: bug, minor change

#21 Synchronized with master
  README.md
  md/_resources.md
Labels: minor change

#23 it ain't much but it's honest work
  yaml/browserExtensions.yml
Labels: documentation

#24 Synchronization with translation branch
  yaml/browserExtensions.yml
Labels: minor change
